# Book settings
title: "ASC-ODE Documentation"
author: "Fan Xiaowen, Immaculada Fern√°ndez, Zeynep Yanmaz, Ahmad Zulafqar"
logo: ASC_Logo_transparent_300ppi_RGB.png

execute:
  execute_notebooks: "auto"

html:
  use_repository_button: false
  use_issues_button: false
